import 'dotenv/config';
import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';
import 'reflect-metadata';
import * as swaggerJSDoc from 'swagger-jsdoc';
import * as swaggerStats from 'swagger-stats';
import * as swaggerUi from 'swagger-ui-express';
import {AppDataSource} from './data-source';
import routes from './routes';

// only let listed origins call us
function corsMw() {
  const raw = process.env.CORS_ORIGINS;
  if (!raw) throw new Error('CORS_ORIGINS is not set');
  const allow = raw.split(',').map(s => s.trim()).filter(Boolean);
  return cors({
    origin(origin, cb) {
      if (!origin) return cb(null, true);
      cb(null, allow.includes(origin));
    },
    credentials: true,
    allowedHeaders: ['Authorization', 'Content-Type'],
    maxAge: 600,
  });
}

// basic per-ip limit on /auth/*
function loginLimit(max = 10) {
  const hits = new Map<string, {n: number; until: number}>();
  const window = 60 * 1000;

  return (req: express.Request, res: express.Response, next: express.NextFunction) => {
    const key = req.ip;
    const now = Date.now();
    let b = hits.get(key);
    if (!b || b.until < now) {
      b = {n: 0, until: now + window};
      hits.set(key, b);
    }
    b.n++;
    res.setHeader('X-RateLimit-Limit', String(max));
    res.setHeader('X-RateLimit-Remaining', String(Math.max(0, max - b.n)));
    if (b.n > max) {
      res.status(429).send({error: 'too many attempts'});
      return;
    }
    next();
  };
}

// gate the docs/stats UI behind an env-injected token
function adminOnly(req: express.Request, res: express.Response, next: express.NextFunction) {
  const expected = process.env.ADMIN_API_TOKEN;
  if (!expected) return res.status(404).send();
  if (req.headers['x-admin-token'] !== expected) return res.status(404).send();
  next();
}

const swaggerSpec = swaggerJSDoc({
  swaggerDefinition: {
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  apis: ['**/routes/auth.ts'],
});

AppDataSource.initialize()
  .then(() => {
    const app = express();
    app.disable('x-powered-by');
    app.use(helmet({
      contentSecurityPolicy: {directives: {defaultSrc: ["'none'"], frameAncestors: ["'none'"]}},
      hsts: {maxAge: 31536000, includeSubDomains: true, preload: false},
      referrerPolicy: {policy: 'no-referrer'},
      frameguard: {action: 'deny'},
    } as any));
    app.use(corsMw());
    app.use(bodyParser.json({limit: '64kb'}));
    app.use(morgan('[:date[iso]] :method :url :status :res[content-length] :response-time ms'));

    app.use('/swagger-stats', adminOnly, swaggerStats.getMiddleware({uriPath: '/swagger-stats'}));
    app.use('/api-docs', adminOnly, swaggerUi.serve, swaggerUi.setup(swaggerSpec));

    app.use('/auth', loginLimit());
    app.use('/', routes);

    const port = parseInt(process.env.PORT || '3000', 10);
    app.listen(port, () => console.log(`Server started on port ${port}!`));
  })
  .catch(e => {
    console.error('startup failed:', e);
    process.exit(1);
  });
