version: "3"

services:
  front:
    build:
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-localhost:3000}
    container_name: front_front_1
    restart: always
    ports:
      - "8080:8080"
